version: '2'
services:
  web:
    build: .
    environment:
      CI_JOB_TOKEN: job_t0ke9
      CI_PROJECT_URL: https://gitlab.com/username/monorepo
      CI_PROJECT_ID: 1
      CI_JOB_NAME: build-flask
      CI_COMMIT_REF_SLUG: feature-back-0001
      CI_COMMIT_REF_NAME: feature/BACK-0001
      CIS_SERVICE_REGEXP: ^build-([\w]{1,})$$
      CIS_SERVICE_PATH: src
      CIS_DEPENDENCIES_MAP: |
        src/flask:
          - src/python
        src/python:
          - requirements.txt
        src/mariadb:
          - src/liquibase
    command: python3 -m japronto run.app --reload
    working_dir: /opt/python
    volumes:
      - ./:/opt/python
    ports:
      - 8080:80
